 #ifndef CAUSEOFRESET_H
#define CAUSEOFRESET_H

#include "Arduino.h"
/*
 #define mLOW_POWER_RESET __HAL_RCC_GET_FLAG(RCC_FLAG_LPWRRST)
#define mWINDOW_WATCHDOG_RESET __HAL_RCC_GET_FLAG(RCC_FLAG_WWDGRST)
#define mINDEPENDENT_WATCHDOG_RESET __HAL_RCC_GET_FLAG(RCC_FLAG_IWDGRST)
#define mSOFTWARE_RESET __HAL_RCC_GET_FLAG(RCC_FLAG_SFTRST)
#define mPOWER_ON_RESET __HAL_RCC_GET_FLAG(RCC_FLAG_PORRST)
#define mEXTERNAL_RESET_PIN_RESET __HAL_RCC_GET_FLAG(RCC_FLAG_PINRST)
#define mBROWNOUT_RESET __HAL_RCC_GET_FLAG(RCC_FLAG_BORRST)
*/

#define mLOW_POWER_RESET (0)
#define mWINDOW_WATCHDOG_RESET (0)
#define mSOFTWARE_RESET (0)
#define mPOWER_ON_RESET (MCUSR & (1<<PORF))
#define mEXTERNAL_RESET_PIN_RESET (MCUSR & (1<<EXTRF))
#define mBROWNOUT_RESET (MCUSR & (1<<BORF))
#define mINDEPENDENT_WATCHDOG_RESET (MCUSR & (1<<WDRF))

typedef enum
{
    TO_THE_DETERMINED,
    LOW_POWER_RESET,
    WINDOW_WATCHDOG_RESET,
    INDEPENDENT_WATCHDOG_RESET,
    SOFTWARE_RESET,
    POWER_ON_RESET,
    POWER_DOWN_RESET,
    EXTERNAL_RESET_PIN_RESET,
    BROWNOUT_RESET,
    UNKNOWN,

}eCauseOfReset;

eCauseOfReset CauseOfReset(void);

#endif // CAUSEOFRESET_H
